sleep 2;
player saveStatus "juriy_status_mik5"; 
e1 saveStatus "sergant_status_mik2"; 
s1 saveStatus "units1_status_mik2"; 
s1_1 saveStatus "units11_status_mik2"; 
s1_2 saveStatus "units12_status_mik2";
s1_3 saveStatus "units13_status_mik2"; 
s1_4 saveStatus "units14_status_mik2";
s1_5 saveStatus "units15_status_mik2";
s1_6 saveStatus "units16_status_mik2";
s1_7 saveStatus "units17_status_mik2";
spec1 saveStatus "spec1_status_mik1";
spec2 saveStatus "spec2_status_mik1";
sleep 2;
task1 setTaskState "SUCCEEDED";
pioneer=[objNull, objNull, task1, "SUCCEEDED"] execVM "CA\Modules\MP\data\scriptCommands\taskHint.sqf";
sleep 3;
titlecut ["","BLACK out",3];
3 fadeMusic 0;
3 fadesound 0;
sleep 3;
endMission "END1";
