titleCut ["","Black faded",7];
_log_briefing = player createDiaryRecord ["Diary", [localize "STRD_Plan_title", localize "STRD_Plan"]];
_log_briefing = player createDiaryRecord ["Diary", [localize "STRD_Plan_title1", localize "STRD_Plan1"]];
p1 kbAddTopic ["briefing", "kb\briefing.bikb", ""];
p2 kbAddTopic ["briefing", "kb\briefing.bikb", ""];
p3 kbAddTopic ["briefing", "kb\briefing.bikb", ""];
e1 kbAddTopic ["briefing", "kb\briefing.bikb", ""];
player kbAddTopic ["briefing", "kb\briefing.bikb", "", {call compile preprocessFileLineNumbers "kb\briefing_cooper.sqf"}];
task1 = player createSimpleTask [localize "STRD_Task1"];
task1 setSimpleTaskDescription[localize "STRD_Task1_1", localize "STRD_Task1", localize "STRD_Task1"];
player setCurrentTask task1;
p1 switchmove "RepairingKneel";
p=[] execvm "speech.sqf";
p=[] execvm "speech2.sqf";
p=[] execvm "speech3.sqf";
p=[] execvm "markers.sqf";
p=[] execvm "health.sqf";
score = 1;
gun = false;
player loadStatus "juriy_status_mik2"; 
sleep 5;
titleCut ["","Black in",4];
sleep 4;
playsound "STRD_PIO13";
sleep 5;
playmusic "Heaven";
while {alive p3} do {p3 playmove "AmovPercMstpSnonWnonDnon_carCheckWheel"}; 