p = [] execvm "light.sqf";
_log_briefing = player createDiaryRecord ["Diary", [localize "STRD_Plan_title", localize "STRD_Plan"]];
_log_briefing = player createDiaryRecord ["Diary", [localize "STRD_Plan_title1", localize "STRD_Plan1"]];
task1 = player createSimpleTask [localize "STRD_Task1"];
task1 setSimpleTaskDescription[localize "STRD_Task1_1", localize "STRD_Task1", localize "STRD_Task1"];
player setCurrentTask task1;
aerial = false;
alarm = false;
allow = true;
go = true;
st_1 disableAI "MOVE";
titleCut ["","Black faded",7];
0 fademusic 1;
_array2 = [w1, s1_1, s1_2, s1_3, s1_4, s1_7, s1_6, player];
{removeallweapons _x} forEach _array2;
sleep 1;
player loadStatus "juriy_status_mik5"; 
w1 loadStatus "units1_status_mik2"; 
s1_1 loadStatus "units11_status_mik2"; 
s1_2 loadStatus "units12_status_mik2";
s1_3 loadStatus "units13_status_mik2"; 
s1_4 loadStatus "units14_status_mik2";
s1_6 loadStatus "units16_status_mik2";
s1_7 loadStatus "units17_status_mik2";
spec1 loadStatus "spec1_status_mik1";
spec2 loadStatus "spec2_status_mik1";
p=[] execvm "eraser.sqf";
sleep 2;
titleCut ["","Black in",3];
playmusic "Tour";
p=[] execvm "health.sqf";
score = 1;
clearweaponCargo crate;
clearmagazineCargo crate;
sleep 0.5;
crate addweaponcargo ["SMAW", 1]; 
crate addmagazinecargo ["SMAW_HEAA", 6]; 
waitUntil { {(west knowsabout _x) > 3} count _array2 > 0};
alarm = true; 
st_1 setunitpos "DOWN"; 