sleep 2;
player saveStatus "juriy_status_mik6"; 
w1 saveStatus "units1_status_mik3"; 
s1_1 saveStatus "units11_status_mik3"; 
s1_2 saveStatus "units12_status_mik3";
s1_3 saveStatus "units13_status_mik3"; 
s1_4 saveStatus "units14_status_mik3";
s1_6 saveStatus "units16_status_mik3";
s1_7 saveStatus "units17_status_mik3";
spec1 saveStatus "spec1_status_mik2";
spec2 saveStatus "spec2_status_mik2";
sleep 2;
task2 setTaskState "SUCCEEDED";
pioneer=[objNull, objNull, task2, "SUCCEEDED"] execVM "CA\Modules\MP\data\scriptCommands\taskHint.sqf";
sleep 3;
titlecut ["","BLACK out",3];
3 fadeMusic 0;
3 fadesound 0;
sleep 3;
endMission "END1";
