titleCut ["","Black faded",7];
0 fadesound 0;
_log_briefing = player createDiaryRecord ["Diary", [localize "STRD_Plan_title", localize "STRD_Plan"]];
_log_briefing = player createDiaryRecord ["Diary", [localize "STRD_Plan_title1", localize "STRD_Plan1"]];
task1 = player createSimpleTask [localize "STRD_Task1"];
task1 setSimpleTaskDescription[localize "STRD_Task1_1", localize "STRD_Task1", localize "STRD_Task1"];
player setCurrentTask task1;
art = false;
go = false;
go2 = false;
go3 = false;
proval = true;
_array = [w1, e1, s1_1, s1_2, s1_3, s1_4, s1_7, s1_6, player];
{removeallweapons _x} forEach _array;
sleep 1;
player loadStatus "juriy_status_mik6";
e1 loadStatus "sergant_status_mik2";  
w1 loadStatus "units1_status_mik3"; 
of loadStatus "units15_status_mik2";
s1_1 loadStatus "units11_status_mik3"; 
s1_2 loadStatus "units12_status_mik3";
s1_3 loadStatus "units13_status_mik3"; 
s1_4 loadStatus "units14_status_mik3";
s1_6 loadStatus "units16_status_mik3";
s1_7 loadStatus "units17_status_mik3";
spec1 loadStatus "spec1_status_mik2";
spec2 loadStatus "spec2_status_mik2";
sleep 1;
p=[] execvm "eraser.sqf";
score = 1;
sleep 2;
p=[] execvm "proval.sqf";
p=[] execvm "health.sqf";
btr_1 allowdammage false;
player removeWeapon "Binocular"; 
player addweapon "Binocular_Vector";
player kbAddTopic ["briefing", "briefing.bikb", ""];
lisa kbAddTopic ["briefing", "briefing.bikb", ""];
1 fademusic 0.6;
setAccTime 1;
sleep 7;
2 fadesound 1;
titleCut ["","Black in",6]; 
btr_1 hideobject false;
btr_2 hideobject false;
clearweaponCargo crate;
clearmagazineCargo crate;
sleep 0.5;
crate addweaponcargo ["AK_47_M", 2];
crate addweaponcargo ["AKS_74", 3]; 
crate addmagazinecargo ["30Rnd_545x39_AK", 15]; 
crate addmagazinecargo ["30Rnd_762x39_AK47", 10]; 
crate addweaponcargo ["AK_74_GL_kobra", 1]; 
crate addmagazinecargo ["1Rnd_HE_GP25", 10]; 
crate addmagazinecargo ["HandGrenade_East", 30]; 
crate addweaponcargo ["SVD", 1];
crate addmagazinecargo ["10Rnd_762x54_SVD", 5]; 
crate addweaponcargo ["RPG7V", 3]; 
crate addmagazinecargo ["PG7V", 7]; 
crate addweaponcargo ["MetisLauncher", 2];
crate addmagazinecargo ["AT13", 6];
crate addweaponcargo ["huntingrifle", 1];
crate addmagazinecargo ["5x_22_LR_17_HMR", 6];
crate addweaponcargo ["PK", 1]; 
crate addmagazinecargo ["100Rnd_762x54_PK", 4]; 
crate addweaponcargo ["Sa58P_EP1", 3]; 
crate addmagazinecargo ["30Rnd_762x39_SA58", 15]; 
sleep 4;
playmusic "Oblivion";
sleep 300;
go2 = true;
lisa kbTell [player, "briefing", "STRD_PIO12"];
waitUntil {lisa kbWasSaid [player, "briefing", "STRD_PIO12", 1]};
art = true;
playmusic "Steel";
sleep 68;
Bo="Bo_GBU12_LGB" createVehicle getPos aeria; 
go = true;
lisa kbTell [player, "briefing", "STRD_PIO13"];
waitUntil {lisa kbWasSaid [player, "briefing", "STRD_PIO13", 1]};
sleep 140;
go3 = true;
lisa kbTell [player, "briefing", "STRD_PIO14"];
waitUntil {lisa kbWasSaid [player, "briefing", "STRD_PIO14", 1]};




